title:            about alice
url:              https://alicecai.github.io
permalink:        pretty
highlighter:      pygments
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
google_analytics: UA-45273196-2
timezone:         New York 
paginate: 5
gems: 
  - jemoji
