title:            Hi there.
url:              https://alicecai.github.io/about
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
google_analytics: UA-45273196-2
timezone:         New York 
paginate: 5
links: 
  - name:         About
    url:          /about